### PR TITLE
Fixed CRAN issues with errors related to API rate limits (patch fix)

### LINKED ISSUE #126: Add more informative error message for bibstats functions
Add a more graceful/informative error message and for us to include limits so that the API is not overwhelmed within the bibstats family of functions.

### PR DESCRIPTION
**Pull request by henriquesposito**
# Description

This patch PR fixes CRAN issues with API rate limits.

## Package updates:

- Closed #126 by adding more informative message for when `percent_female()` reaches API rate limits
- Skipped `bibstats` functions tests on linux

## Thesis

- Added packages to 'thesis_pdf' template to improve rendering

# Checklist:

- [x] PR form
  - [x] I have given this pull request an informative title
  - [x] Description above itemizes changes under subtitles, e.g. "## Collection""
  - [x] Any closed, fixed, or related issues are referenced and explained in the description above, e.g. "Fixed #0 by adding A"
  - [x] Package builds on my OS without issues
- [x] PR checks all pass for latest commit
  - [x] Package builds on Mac
  - [x] Package builds on Windows
  - [x] Package builds on Linux
  - [x] CodeCov check: Package improves or maintains good test coverage
  - [x] CodeFactor check: Package improves or maintains good style
- [x] Documentation
  - [x] Any new or modified functions or data have roxygen style documentation in their .R scripts
  - [x] Any longer functions are commented inline so that it is easier to debug in the future
  - [x] PR description above and the NEWS.md file are aligned
  - [x] DESCRIPTION file version is bumped by the appropriate increment (major, minor, patch)

### CODE REVIEW

File: DESCRIPTION [hunk 1]
```diff
@@ -20,9 +20,13 @@ Authors@R:
...
            family = "Bieri",
-           role = c("ctb"),
+           role = "ctb",
            email = "bernhard.bieri@graduateinstitute.ch",
-           comment = c(ORCID = "0000-0001-5943-9059"))
+           comment = c(ORCID = "0000-0001-5943-9059")),
+      person(given = "Henrique",
+           family = "Sposito",
+           role = "ctb",
+           comment = c(ORCID = "0000-0003-3420-6085"))
```
Comment (jhollway) [inline DESCRIPTION:29]: Thanks @henriquesposito !

File: R/bibstats.R [hunk 2]
```diff
@@ -76,10 +81,17 @@ percent_female <- function(bib_file,
...
-    gender <- sapply(authors,
-                     function(x) any(gender::gender(x, method = "genderize")$gender == "female"))
-    paste0(round(sum(gender) / length(gender), 2) * 100,
-                 "% female authors")
+    gender <- tryCatch({
+      sapply(authors, function(x)
+        any(gender::gender(x, method = "genderize")$gender == "female"))
+      },
+      message = "Rate limit for the `{gender}` R package has been reached due to the amount of download requests.
+      Please wait a few hours and try again later."
```
Comment (jhollway) [inline R/bibstats.R:89]: Do we need to force a slow down in requests somehow so that the package is not being 'antisocial'?

**Review by jhollway — APPROVED** [review]
